title: Totally Indescribable
email: c.ed.mead@gmail.com
description: >
  Code, web development, and textbook solutions in graduate mathematics
baseurl: ""
url: ""
github:
  is_user_page: true
  owner_name: cemulate
  owner_url: https://github.com/cemulate

collections:
  math_solutions:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: math_solutions
    values:
      auto_description: true

sass:
  load_paths:
    - _sass

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - node_modules
