title: Totally Indescribable
email: c.ed.mead@gmail.com
description: >
  Code, web development, and textbook solutions in graduate mathematics
baseurl: ""
url: ""
github:
  is_user_page: true
  owner_name: cemulate
  owner_url: https://github.com/cemulate

collections:
  project_descriptions:
    output: false
  web_component_descriptions:
    output: false
  solutions_hatcher:
    textbook_author: Allen Hatcher
    textbook_name: Algebraic Topology
    description: Various solutions through chapter 3 (homology and some cohomology)
    output: true
  solutions_leinster:
    textbook_author: Tom Leinster
    textbook_name: Basic Category Theory
    description: Solutions to assorted exercises from the whole book
    output: true
  solutions_massey:
    textbook_author: William Massey
    textbook_name: Algebraic Topology
    description: A few solutions from the chapters over fundamental group and covering space theory
    output: true
  solutions_sipser:
    textbook_author: Michael Sipser
    textbook_name: Theory of Computation
    description: Assorted solutions covering finite automata theory
    output: true
  solutions_maclane:
    textbook_author: MacLane and Moerdijk
    textbook_name: Sheaves in Geometry and Logic
    description: Solutions to exercises and proofs of theorems in introductory topos theory
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  load_paths:
    - _sass

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - node_modules

plugins:
  - jekyll-redirect-from
